---
title: "Making TraMA - January 2024"
author: "Eric Klopack"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Packages

```{r}
suppressPackageStartupMessages({
library(data.table)
library(tidyverse)
})
set.seed(1234)
```

# Making Score

```{r}
# Load Libraries
library(tidyverse)


# Making the surrogate function
  # This function expects rows to be genes, columns to be observations
surrogate <- function(data, coefs, age_col, idvar, 
                      min.perc = 0, ref_panel = NULL) {
    # What are the genes available in the data?
    gene.names <- as.character(rownames(data))
    
    # This is a probably unnecessary check that the first column is ensembl IDs
    if (length(grep("ENSG", gene.names)) == 0) {
      stop("First column should contain ensembl IDs")
    }
    
    # Remove the gene column and transpose the data; then make the genes into 
    # column names 
    data <- t(as.matrix(data))
    colnames(data) <- gene.names
    
    # Add ages
    
    data <- as.data.frame(data) %>% 
      rownames_to_column(var = idvar) %>% 
      full_join(age_col, by = idvar) %>% 
      column_to_rownames(var = idvar)
    
    # Create a list of all genes that we have coefficients for that are also in 
    # the data
    gene.names <- as.character(colnames(data))
    mask <- coefs$ensg_id %in% gene.names
    print('Number of missing genes')
    print(table(mask==F))

    # This is a probably unnecessary check that we have at least 80% of the genes
    # needed for the surrogate
    if (mean(mask) > min.perc) {
      
        # Create a list of the coefficients file with only genes that are in the 
        # data
        obs.genes <- coefs$ensg_id[mask]
        miss.genes <- coefs$ensg_id[mask==F]
        # Create a smaller version of the data file with only genes that are in 
        # the coefficients file
        small_data <- data[, obs.genes] %>% 
          mutate_all(as.numeric) 
        
        if (is.null(ref_panel) == T) {
          
          print('It is strongly recommended that you use a reference panel. Without a reference panel, the level and mean of TraMA will be meaningless.')
          
        } else {
          
          if (length(miss.genes) > 0) {
          
          ref.vals <- ref_panel %>% 
            filter(ensg_id %in% miss.genes)
          
          small_data <- as.data.frame(small_data)
          
          for (i in miss.genes) {
            
            small_data[i] <- filter(ref.vals, ensg_id == i)$mean
            
          }
          
          small_data <- small_data %>% 
            select(all_of(coefs$ensg_id))
          
          }}
        
        small_data <- as.matrix(small_data)
        # Do matrix multiplication of the column of coefficients and the matrix 
        # of data
        
        if (is.null(ref_panel) == T) {
          
surrogate <- small_data %*% as.matrix(coefs$coef[coefs$ensg_id %in% obs.genes])
          
        } else {
        
        surrogate <- small_data %*% as.matrix(coefs$coef)
        
    }}
    # This prints the error message if there are too few genes
    else {
        title <- gsub("GA", "", gsub("coef", "", substitute(coefs)))
        warning("The number of missing genes for ", title, 
                " exceeds ", min.perc*100,
                "%.\n  ---> This measure will be NA.\n")
        surrogate <- rep(NA, nrow(data))
    }
    
    surrogate <- -18.07571 + surrogate * 10.02709
    
    surrogate
}
```

```{r}
# This should be your log2cpm matrix, right now assumes it is in the same folder
  # This function expects rows to be genes, columns to be observations, for the 
  # data to be QC'd, normalized, etc. row names should be ensemble IDs and 
  # column names should be observation IDs

l2cpm <- read.table('fake_data_complete.txt')

# This strips the decimal suffix - may be unnecessary for you
rownames(l2cpm) <- gsub("\\..*", "", rownames(l2cpm))

# This should be a table with a column of ids named 'Subject.ID' and a column
  # of subject ages called 'age'
age_col <- read.csv('age_col.csv')

# This is the coefficients file, right now assumes it is in the same folder
TraMA_coefs <- read.csv('TraMA_coefs.csv')

# This is the reference panel of means from HRS
ref_panel <- read.csv('trama_hrs_ref_panel_means.csv')

# This actually makes the score
TraMA <- surrogate(l2cpm, TraMA_coefs, idvar = 'Subject.ID', 
                   age_col = age_col, 
                   ref_panel = ref_panel)

write.csv(TraMA, 'trama_output.csv')

# For the example data, results should be:
# 
# person1   88.54656
# person2   90.01813
# person3   47.21912
# person4   79.57085
# person5  103.06240
# person6  105.32158
# person7   58.60094
# person8   85.43767
# person9   85.75095
# person10  88.58591
```

# EXAMPLE WITH TWO GENES MISSING

```{r}
# # This should be your log2cpm matrix, right now assumes it is in the same folder
#   # This function expects rows to be genes, columns to be observations, for the 
#   # data to be QC'd, normalized, etc. row names should be ensemble IDs and 
#   # column names should be observation IDs
# 
# l2cpm <- read.table('fake_data_missing.txt')
# 
# # This strips the decimal suffix - may be unnecessary for you
# rownames(l2cpm) <- gsub("\\..*", "", rownames(l2cpm))
# 
# # This should be a table with a column of ids named 'Subject.ID' and a column
#   # of subject ages called 'age'
# age_col <- read.csv('age_col.csv')
# 
# # This is the coefficients file, right now assumes it is in the same folder
# TraMA_coefs <- read.csv('TraMA_coefs.csv')
# 
# # This is the reference panel of means from HRS
# ref_panel <- read.csv('trama_hrs_ref_panel_means.csv')
# 
# # This actually makes the score
# TraMA <- surrogate(l2cpm, TraMA_coefs, idvar = 'Subject.ID', 
#                    age_col = age_col, 
#                    ref_panel = ref_panel)
# 
# write.csv(TraMA, 'trama_output.csv')
# 
# # Results should be:
# 
# person1   86.94296
# person2   93.01745
# person3   52.02830
# person4   80.50860
# person5  101.30717
# person6  102.45138
# person7   63.04255
# person8   87.27327
# person9   85.57431
# person10  92.25904
```